! EXEMPLO 10: CARACTERES E STRINGS
PROGRAM STRINGS
CHARACTER NOME
CHARACTER MENSAGEM
INTEGER IDADE

NOME = 'Alice'
MENSAGEM = 'Bem-vindo ao programa com strings'
IDADE = 25

PRINT *, NOME
PRINT *, MENSAGEM
PRINT *, IDADE

END
